export const TABLES = {
  USERS: "users",
  ECOLE: "ecole",
  AVATARS: "avatars",
  ROLE: "role",
  PERMISSION: "permission",
  ROLE_PERMISSION: "role_permission",
  USER_ROLE: "user_role",
  FILIERE: "filiere",
  NIVEAU: "niveau",
  MATIERE: "matiere",
  OPTION: "option",
  FILIERE_NIVEAU: "filiere_niveau",
  FILIERE_OPTION: "filiere_option",
  OPTION_NIVEAU: "option_niveau",
  OPTION_MATIERE: "option_matiere",
  NIVEAU_MATIERE: "niveau_matiere",
  EPREUVE: "epreuve",
  CONTRIBUTION: "contribution",
  TELECHARGEMENT: "telechargement",
  FAVORIS: "favoris",
} as const;
